// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4NODFeV6JFOVqGsXyOgzVfrz92UPOVn4',
    appId: '1:1074137644410:web:70429a4662c77e9b96eac3',
    messagingSenderId: '1074137644410',
    projectId: 'splitmate-julita-2026',
    authDomain: 'splitmate-julita-2026.firebaseapp.com',
    storageBucket: 'splitmate-julita-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsvttnKDGQ1GbWi8LyCZKE_pEent-dP84',
    appId: '1:1074137644410:android:dbd5b5cf192f059096eac3',
    messagingSenderId: '1074137644410',
    projectId: 'splitmate-julita-2026',
    storageBucket: 'splitmate-julita-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAD9s95CPjWt8su5yEVEuJu-pLPj-QuTrE',
    appId: '1:1074137644410:ios:360c60688a932f6496eac3',
    messagingSenderId: '1074137644410',
    projectId: 'splitmate-julita-2026',
    storageBucket: 'splitmate-julita-2026.firebasestorage.app',
    iosBundleId: 'com.example.splitMate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAD9s95CPjWt8su5yEVEuJu-pLPj-QuTrE',
    appId: '1:1074137644410:ios:360c60688a932f6496eac3',
    messagingSenderId: '1074137644410',
    projectId: 'splitmate-julita-2026',
    storageBucket: 'splitmate-julita-2026.firebasestorage.app',
    iosBundleId: 'com.example.splitMate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4NODFeV6JFOVqGsXyOgzVfrz92UPOVn4',
    appId: '1:1074137644410:web:7f8cd699da5c2c2896eac3',
    messagingSenderId: '1074137644410',
    projectId: 'splitmate-julita-2026',
    authDomain: 'splitmate-julita-2026.firebaseapp.com',
    storageBucket: 'splitmate-julita-2026.firebasestorage.app',
  );
}
